//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotionShop.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumableKeeping
    {
        public int IdConsumableKeeping { get; set; }
        public int IdConsumable { get; set; }
        public int Count { get; set; }
        public int IdStorage { get; set; }
    
        public virtual Consumable Consumable { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
