//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotionShop.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumable()
        {
            this.ConsumableKeeping = new HashSet<ConsumableKeeping>();
            this.ConsumablesUsing = new HashSet<ConsumablesUsing>();
        }
    
        public int IdConsumable { get; set; }
        public string Name { get; set; }
        public int IdUnitOfMeasurement { get; set; }
        public int IdType { get; set; }
    
        public virtual TypeConsumable TypeConsumable { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumableKeeping> ConsumableKeeping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumablesUsing> ConsumablesUsing { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
