//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotionShop.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PotionShopEntities : DbContext
    {
        public PotionShopEntities()
            : base("name=PotionShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<BuyerShop> BuyerShop { get; set; }
        public virtual DbSet<Consumable> Consumable { get; set; }
        public virtual DbSet<ConsumableKeeping> ConsumableKeeping { get; set; }
        public virtual DbSet<ConsumablesUsing> ConsumablesUsing { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Marketing> Marketing { get; set; }
        public virtual DbSet<Potion> Potion { get; set; }
        public virtual DbSet<PotionKeeping> PotionKeeping { get; set; }
        public virtual DbSet<PotionType> PotionType { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeConsumable> TypeConsumable { get; set; }
        public virtual DbSet<TypeStorage> TypeStorage { get; set; }
        public virtual DbSet<UnitOfMeasurement> UnitOfMeasurement { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
    }
}
